DROP TABLE USERS;

CREATE TABLE USERS (
	userId INTEGER NOT NULL,
	login VARCHAR(80) NOT NULL,
	password CHAR(32) NOT NULL,
	tipo VARCHAR(13) NOT NULL,
	idOriginal INT,
	
	CONSTRAINT PK_USERS PRIMARY KEY(userId),
	CONSTRAINT CK_TIPO_USUARIO CHECK (tipo IN ('Administrador', 'Escuderia', 'Piloto'))
);

CREATE SEQUENCE IF NOT EXISTS SEQ_USER_ID 
START 1 
NO CYCLE 
OWNED BY USERS.userId;

INSERT INTO USERS VALUES (nextval('SEQ_USER_ID'), 'admin', md5('admin'), 'Administrador', NULL);



